name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: lint verilog code
        uses: SuibianP/verilog-cleaner@v0.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: src/
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: generate document
        uses: TerosTechnology/teroshdl-documenter-action@1.0.0
        with:
          args: -i ./src --recursive --out html --outpath docs/
      - name: upload document
        uses: actions/upload-artifact@v2.2.4
        with:
          name: documentation-html
          path: teroshdl_doc
