name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: install linter
        run: |
          sudo apt-get install verilator
      - name: lint by verilator
        run: |
          cd src/darkriscv/rtl
          verilator --lint-only -Wall *.v
#       - name: lint verilog code
#         uses: SuibianP/verilog-cleaner@v0.1.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           workdir: src/
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: generate document
        uses: TerosTechnology/teroshdl-documenter-action@1.0.0
        with:
          args: -i ./src --recursive --out html --outpath docs/
      - name: upload teroshdl-html
        uses: actions/upload-artifact@v2.2.4
        with:
          name: teroshdl-html
          path: docs/
      - name: deploy document to gh-pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: docs/
